In [1]:
#Importing Necessary Libraries.
import pandas as pd
import os
os.chdir('E:\\COVID\\NonAugmentedTrain')


from PIL import Image
import numpy as np
import os
import cv2
import keras  
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout

Using TensorFlow backend.


In [2]:
# assign lables to each images present under specific classified folders.
# also coverting all images to RGB format so that all images have one standard
# Resolution may be different of images so converting all to 50,50 shape.

data=[]
labels=[]
BacterialPneumonia=os.listdir("E:/COVID/NonAugmentedTrain/BacterialPneumonia/")
for a in BacterialPneumonia:
    try:
        image=cv2.imread("E:/COVID/NonAugmentedTrain/BacterialPneumonia/"+a)
        image_from_array = Image.fromarray(image, 'RGB')
        size_image = image_from_array.resize((50, 50))
        data.append(np.array(size_image))
        labels.append(0)
    except AttributeError:
        print("")
        
COVID=os.listdir("E:/COVID/NonAugmentedTrain/COVID-19/")
for b in COVID:
    try:
        image=cv2.imread("E:/COVID/NonAugmentedTrain/COVID-19/"+b)
        image_from_array = Image.fromarray(image, 'RGB')
        size_image = image_from_array.resize((50, 50))
        data.append(np.array(size_image))
        labels.append(1)
    except AttributeError:
        print("")
        
Normal=os.listdir("E:/COVID/NonAugmentedTrain/Normal/")
for c in Normal:
    try:
        image=cv2.imread("E:/COVID/NonAugmentedTrain/Normal/"+c)
        image_from_array = Image.fromarray(image, 'RGB')
        size_image = image_from_array.resize((50, 50))
        data.append(np.array(size_image))
        labels.append(2)
    except AttributeError:
        print("")

ViralPneumonia=os.listdir("E:/COVID/NonAugmentedTrain/ViralPneumonia/")
for d in ViralPneumonia:
    try:
        image=cv2.imread("E:/COVID/NonAugmentedTrain/ViralPneumonia/"+d)
        image_from_array = Image.fromarray(image, 'RGB')
        size_image = image_from_array.resize((50, 50))
        data.append(np.array(size_image))
        labels.append(3)
    except AttributeError:
        print("")

# labels given are 0,1,2 and 3

In [3]:
Cells=np.array(data)
labels=np.array(labels)

# now cells consist of array of pixels of image and labels consist of corresponding class to it.

In [4]:
# displaying images after classifing them, and converting numberic class to its distinguish categorical class


import matplotlib.pyplot as plt


plt.figure(1 , figsize = (15 , 9))
n = 0 
for i in range(49):
    n += 1 
    r = np.random.randint(0 , Cells.shape[0] , 1)
    plt.subplot(7 , 7 , n)
    plt.subplots_adjust(hspace = 0.5 , wspace = 0.5)
    plt.imshow(Cells[r[0]])
    plt.title('BacterialPneumonia' if labels[r[0]] == 0 else ('COVID' if  labels[r[0]] == 1 else( 'Normal'  if labels[r[0]] == 2 else 'ViralPneumonia' )))
    plt.xticks([]) , plt.yticks([])
    
plt.show()

<Figure size 1500x900 with 49 Axes>

In [5]:
s=np.arange(Cells.shape[0])
np.random.shuffle(s)
Cells=Cells[s]
labels=labels[s]

# shuffling of images so that images should not get trained in serial class order

In [6]:
num_classes=len(np.unique(labels))
len_data=len(Cells)

# assign no. of class for model and determine length 

In [7]:
# train test split
# making data for validation

In [8]:
(x_train,x_test)=Cells[(int)(0.1*len_data):],Cells[:(int)(0.1*len_data)]
x_train = x_train.astype('float32')/255 # As we are working on image data we are normalizing data by divinding 255.
x_test = x_test.astype('float32')/255
train_len=len(x_train)
test_len=len(x_test)

In [9]:
# check shape

In [10]:
x_train.shape

(1802, 50, 50, 3)

In [11]:
x_test.shape

(200, 50, 50, 3)

In [12]:
Cells.shape

(2002, 50, 50, 3)

In [13]:
# As we don't have unseen data for validation purpose so we will take only train data for model building
#instead of taking complete data

#NOTE: Accuracy can be imporved in future by taking complete data for model building 

In [16]:
# assign labels

(y_train,y_test)=labels[(int)(0.1*len_data):],labels[:(int)(0.1*len_data)]
A=y_test
y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)

In [19]:
# saved classes before transforming it to array
A

array([2, 2, 2, 2, 0, 3, 3, 2, 3, 0, 0, 0, 2, 0, 0, 3, 2, 0, 2, 0, 2, 2,
       2, 2, 2, 3, 2, 0, 3, 1, 0, 3, 0, 2, 2, 3, 2, 0, 3, 2, 0, 0, 2, 3,
       3, 0, 3, 3, 2, 2, 3, 3, 0, 2, 2, 2, 2, 0, 2, 2, 0, 3, 2, 1, 3, 3,
       2, 3, 3, 1, 2, 2, 3, 0, 0, 1, 2, 2, 3, 0, 0, 0, 0, 2, 2, 1, 0, 2,
       2, 3, 2, 0, 2, 3, 3, 2, 2, 3, 3, 2, 2, 0, 0, 3, 2, 3, 2, 0, 3, 0,
       1, 0, 2, 3, 0, 2, 0, 3, 3, 2, 0, 2, 3, 2, 0, 0, 3, 0, 2, 2, 3, 0,
       3, 2, 2, 2, 3, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 3, 2, 2, 2, 0, 0, 2,
       0, 2, 2, 0, 3, 0, 3, 2, 3, 3, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 2,
       0, 2, 2, 0, 2, 0, 1, 2, 2, 0, 3, 0, 3, 3, 0, 2, 1, 0, 2, 2, 0, 3,
       0, 1])

In [20]:
y_test

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],


In [21]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
# Creating model

In [23]:
#creating sequential model
# Accuracy can be improve in future by changing parameters and no. assign to parameters

model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(50,50,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(4,activation="softmax"))# represent output layer neurons 
model.summary()






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 50, 50, 16)        208       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 32)        2080      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 64)        8256      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 6, 6, 64)          0         
______________________

In [24]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=50,epochs=15,validation_data=(x_test, y_test))




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 1802 samples, validate on 200 samples
Epoch 1/15





1802/1802 [==============================] - 7s 4ms/step - loss: 1.0210 - acc: 0.5427 - val_loss: 0.8399 - val_acc: 0.6150
Epoch 2/15
1802/1802 [==============================] - 6s 3ms/step - loss: 0.6512 - acc: 0.7370 - val_loss: 0.6757 - val_acc: 0.7150
Epoch 3/15
1802/1802 [==============================] - 7s 4ms/step - loss: 0.5380 - acc: 0.7780 - val_loss: 0.5794 - val_acc: 0.7000
Epoch 4/15
1802/1802 [==============================] - 7s 4ms/step - loss: 0.4962 - acc: 0.7913 - val_loss: 0.5590 - val_acc: 0.7100
Epoch 5/15
1802/1802 [==============================] - 7s 4ms/step - loss: 0.5052 - acc: 0.7786 - val_loss: 0.5292 - val_acc: 0.7500
Epoch 6/15
1802/1802 [==============================] - 5s 3ms/step - loss: 0.4612 - acc: 0.7913 - val_loss: 0.5239 - val_acc: 0.7250
Epoch 7/15
1802/1802 [=======================

In [25]:
# accuracy can be again improved by increasing number of epochs 

In [28]:
# Evaluation

model.evaluate(x_test, y_test)


200/200 [==============================] - 0s 860us/step


[0.465653567314148, 0.765]

In [29]:
# predict probabilities for test set
yhat_probs = model.predict(x_test, verbose=0)
# predict classes for test set
yhat_classes = model.predict_classes(x_test, verbose=0)

In [31]:
# Prediction
yhat_classes

array([2, 2, 2, 2, 3, 3, 0, 2, 0, 3, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2,
       2, 2, 2, 0, 2, 0, 3, 1, 0, 0, 0, 2, 2, 3, 2, 3, 0, 2, 3, 0, 2, 0,
       0, 0, 3, 0, 2, 2, 0, 3, 0, 2, 2, 2, 2, 0, 2, 2, 3, 0, 2, 1, 0, 0,
       2, 0, 0, 1, 2, 3, 0, 0, 0, 1, 2, 2, 3, 0, 0, 0, 3, 2, 2, 1, 0, 2,
       2, 3, 2, 0, 2, 0, 0, 2, 2, 3, 0, 2, 2, 3, 0, 0, 2, 0, 2, 0, 0, 0,
       1, 0, 2, 3, 3, 2, 0, 0, 3, 2, 0, 2, 3, 2, 0, 0, 3, 3, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 1, 2, 2, 2, 0, 0, 2,
       0, 2, 2, 0, 0, 0, 0, 2, 3, 3, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 3, 2,
       0, 2, 2, 0, 2, 0, 1, 2, 2, 3, 0, 0, 3, 3, 3, 2, 0, 0, 2, 2, 0, 2,
       3, 1], dtype=int64)

In [34]:
# calling back actuals
A

array([2, 2, 2, 2, 0, 3, 3, 2, 3, 0, 0, 0, 2, 0, 0, 3, 2, 0, 2, 0, 2, 2,
       2, 2, 2, 3, 2, 0, 3, 1, 0, 3, 0, 2, 2, 3, 2, 0, 3, 2, 0, 0, 2, 3,
       3, 0, 3, 3, 2, 2, 3, 3, 0, 2, 2, 2, 2, 0, 2, 2, 0, 3, 2, 1, 3, 3,
       2, 3, 3, 1, 2, 2, 3, 0, 0, 1, 2, 2, 3, 0, 0, 0, 0, 2, 2, 1, 0, 2,
       2, 3, 2, 0, 2, 3, 3, 2, 2, 3, 3, 2, 2, 0, 0, 3, 2, 3, 2, 0, 3, 0,
       1, 0, 2, 3, 0, 2, 0, 3, 3, 2, 0, 2, 3, 2, 0, 0, 3, 0, 2, 2, 3, 0,
       3, 2, 2, 2, 3, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 3, 2, 2, 2, 0, 0, 2,
       0, 2, 2, 0, 3, 0, 3, 2, 3, 3, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 2,
       0, 2, 2, 0, 2, 0, 1, 2, 2, 0, 3, 0, 3, 3, 0, 2, 1, 0, 2, 2, 0, 3,
       0, 1])

In [47]:
from sklearn.metrics import classification_report
print(classification_report(A, yhat_classes))

              precision    recall  f1-score   support

           0       0.61      0.79      0.69        62
           1       0.90      0.90      0.90        10
           2       0.99      0.98      0.98        81
           3       0.53      0.34      0.42        47

    accuracy                           0.77       200
   macro avg       0.76      0.75      0.75       200
weighted avg       0.76      0.77      0.75       200



In [40]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(A, yhat_classes)
print('Accuracy: %f' % accuracy)
precision = precision_score(A, yhat_classes,average='weighted')
print('Precision: %f' % precision)
recall = recall_score(A, yhat_classes,average='weighted')
print('Recall: %f' % recall)
f1 = f1_score(A, yhat_classes,average='weighted')
print('F1 score: %f' % f1)

Accuracy: 0.765000
Precision: 0.760146
Recall: 0.765000
F1 score: 0.754059


# Summary

COVID cases are able to be classified with 90% of assurance so keeping this model as best solution for now.
Where as F1 score for class 3 (Viral Pneumonia) is low but not a problem as they are getting misclassified but are getting 
classified to class 1 which is Bacterical Pneumonia. Hence as per domain both cases belongs to same family and hence classifing them as one of the alternate class is acceptable.

Note: 1. To increase F1 score of COVID, duplicate images were made in the image folder itself, but didn't change the F1 score much so the approach was discarded.

2. Augmentation technique was performed on the images but that increased the number of images for other class because of which F1 score came down. Hence approch was removed.
Where as performing augmentation on covid class didn't help to improve performance.

3.The code was rerun again because of which accuracy went down.
The model which was deployed got a accuracy of 85% and the F1 score was about 80%.

Reason:
Neural network algorithms are stochastic. This means they make use of randomness, such as initializing to random weights, and in turn the same network trained on the same data can produce different results.

4. COVID cases images were only 60 in data available of which model is train only about 50 images.
Hence the result predicted by the model for real unseen data may not be correct as model in not trained on sufficient evidences.